/*
 * Decompiled with CFR 0.152.
 */
package com.desertstormfront.ui.hud;

import com.desertstormfront.app.support.TextFormatter;
import com.desertstormfront.config.GameConfig;
import com.desertstormfront.game.player.PlayerStatistics;
import com.desertstormfront.ui.Align;
import com.desertstormfront.ui.Image;
import com.desertstormfront.ui.Label;
import com.desertstormfront.ui.TextureRegion;
import com.desertstormfront.ui.hud.GuiAssets;
import com.desertstormfront.ui.hud.OkDialog;
import com.noblemaster.lib.i18n.Messages;

public final class ScoreDialog
extends OkDialog {
    private Label unitsPlayerShadow;
    private Label unitsPlayer;
    private Label unitsEnemyShadow;
    private Label unitsEnemy;
    private Label damagePlayerShadow;
    private Label damagePlayer;
    private Label damageEnemyShadow;
    private Label damageEnemy;
    private Label basesPlayerShadow;
    private Label basesPlayer;
    private Label basesEnemyShadow;
    private Label basesEnemy;
    private Image m;
    private Image n;
    private Image o;

    public ScoreDialog() {
        super(new TextureRegion(967, 622, 540, 388));
        boolean i1 = GameConfig.isDarkTheme();
        Label label = i1 ? new Label(GuiAssets.getDefaultFont(), true) : new Label(GuiAssets.getFontDokchampa15());
        label.setText(i1 ? Messages.get("Player[i18n]: Player") : Messages.getFallback("Player[i18n]: Player"));
        label.setMaxWidth(75);
        label.setX(275.0f);
        label.setY(58.0f);
        label.a(-8355712);
        label.setAlign(Align.CENTER);
        this.addChild(label);
        Label label2 = i1 ? new Label(GuiAssets.getDefaultFont(), true) : new Label(GuiAssets.getFontDokchampa15());
        label2.setText(i1 ? Messages.get("Enemy[i18n]: Enemy") : Messages.getFallback("Enemy[i18n]: Enemy"));
        label2.setMaxWidth(75);
        label2.setX(360.0f);
        label2.setY(58.0f);
        label2.a(-8355712);
        label2.setAlign(Align.CENTER);
        this.addChild(label2);
        Label label3 = i1 ? new Label(GuiAssets.getDefaultFont(), true) : new Label(GuiAssets.getFontDokchampa15());
        label3.setText(i1 ? Messages.get("UnitsDestroyedLost[i18n]: Units Destroyed/Lost") : Messages.getFallback("UnitsDestroyedLost[i18n]: Units Destroyed/Lost"));
        label3.setX(59.0f);
        label3.setY(91.0f);
        label3.a(-6250336);
        this.addChild(label3);
        this.unitsPlayerShadow = new Label(GuiAssets.getDefaultFont());
        this.unitsPlayerShadow.setMaxWidth(75);
        this.unitsPlayerShadow.setX(276.0f);
        this.unitsPlayerShadow.setY(92.0f);
        this.unitsPlayerShadow.a(-16777216);
        this.unitsPlayerShadow.setAlign(Align.CENTER);
        this.addChild(this.unitsPlayerShadow);
        this.unitsPlayer = new Label(GuiAssets.getDefaultFont());
        this.unitsPlayer.setMaxWidth(75);
        this.unitsPlayer.setX(275.0f);
        this.unitsPlayer.setY(91.0f);
        this.unitsPlayer.a(-7168);
        this.unitsPlayer.setAlign(Align.CENTER);
        this.addChild(this.unitsPlayer);
        this.unitsEnemyShadow = new Label(GuiAssets.getDefaultFont());
        this.unitsEnemyShadow.setMaxWidth(75);
        this.unitsEnemyShadow.setX(361.0f);
        this.unitsEnemyShadow.setY(92.0f);
        this.unitsEnemyShadow.a(-16777216);
        this.unitsEnemyShadow.setAlign(Align.CENTER);
        this.addChild(this.unitsEnemyShadow);
        this.unitsEnemy = new Label(GuiAssets.getDefaultFont());
        this.unitsEnemy.setMaxWidth(75);
        this.unitsEnemy.setX(360.0f);
        this.unitsEnemy.setY(91.0f);
        this.unitsEnemy.a(-65536);
        this.unitsEnemy.setAlign(Align.CENTER);
        this.addChild(this.unitsEnemy);
        Label label4 = i1 ? new Label(GuiAssets.getDefaultFont(), true) : new Label(GuiAssets.getFontDokchampa15());
        label4.setText(i1 ? Messages.get("DamageInflicedSustained[i18n]: Damage Inflicted/Sustained") : Messages.getFallback("DamageInflicedSustained[i18n]: Damage Inflicted/Sustained"));
        label4.setX(59.0f);
        label4.setY(123.0f);
        label4.a(-6250336);
        this.addChild(label4);
        this.damagePlayerShadow = new Label(GuiAssets.getDefaultFont());
        this.damagePlayerShadow.setMaxWidth(75);
        this.damagePlayerShadow.setX(276.0f);
        this.damagePlayerShadow.setY(124.0f);
        this.damagePlayerShadow.a(-16777216);
        this.damagePlayerShadow.setAlign(Align.CENTER);
        this.addChild(this.damagePlayerShadow);
        this.damagePlayer = new Label(GuiAssets.getDefaultFont());
        this.damagePlayer.setMaxWidth(75);
        this.damagePlayer.setX(275.0f);
        this.damagePlayer.setY(123.0f);
        this.damagePlayer.a(-7168);
        this.damagePlayer.setAlign(Align.CENTER);
        this.addChild(this.damagePlayer);
        this.damageEnemyShadow = new Label(GuiAssets.getDefaultFont());
        this.damageEnemyShadow.setMaxWidth(75);
        this.damageEnemyShadow.setX(361.0f);
        this.damageEnemyShadow.setY(124.0f);
        this.damageEnemyShadow.a(-16777216);
        this.damageEnemyShadow.setAlign(Align.CENTER);
        this.addChild(this.damageEnemyShadow);
        this.damageEnemy = new Label(GuiAssets.getDefaultFont());
        this.damageEnemy.setMaxWidth(75);
        this.damageEnemy.setX(360.0f);
        this.damageEnemy.setY(123.0f);
        this.damageEnemy.a(-65536);
        this.damageEnemy.setAlign(Align.CENTER);
        this.addChild(this.damageEnemy);
        Label label5 = i1 ? new Label(GuiAssets.getDefaultFont(), true) : new Label(GuiAssets.getFontDokchampa15());
        label5.setText(i1 ? Messages.get("BasesCapturedLost[i18n]: Bases Captured/Lost") : Messages.getFallback("BasesCapturedLost[i18n]: Bases Captured/Lost"));
        label5.setX(59.0f);
        label5.setY(155.0f);
        label5.a(-6250336);
        this.addChild(label5);
        this.basesPlayerShadow = new Label(GuiAssets.getDefaultFont());
        this.basesPlayerShadow.setMaxWidth(75);
        this.basesPlayerShadow.setX(276.0f);
        this.basesPlayerShadow.setY(156.0f);
        this.basesPlayerShadow.a(-16777216);
        this.basesPlayerShadow.setAlign(Align.CENTER);
        this.addChild(this.basesPlayerShadow);
        this.basesPlayer = new Label(GuiAssets.getDefaultFont());
        this.basesPlayer.setMaxWidth(75);
        this.basesPlayer.setX(275.0f);
        this.basesPlayer.setY(155.0f);
        this.basesPlayer.a(-7168);
        this.basesPlayer.setAlign(Align.CENTER);
        this.addChild(this.basesPlayer);
        this.basesEnemyShadow = new Label(GuiAssets.getDefaultFont());
        this.basesEnemyShadow.setMaxWidth(75);
        this.basesEnemyShadow.setX(361.0f);
        this.basesEnemyShadow.setY(156.0f);
        this.basesEnemyShadow.a(-16777216);
        this.basesEnemyShadow.setAlign(Align.CENTER);
        this.addChild(this.basesEnemyShadow);
        this.basesEnemy = new Label(GuiAssets.getDefaultFont());
        this.basesEnemy.setMaxWidth(75);
        this.basesEnemy.setX(360.0f);
        this.basesEnemy.setY(155.0f);
        this.basesEnemy.a(-65536);
        this.basesEnemy.setAlign(Align.CENTER);
        this.addChild(this.basesEnemy);
        this.m = new Image(new TextureRegion(256, 912, 22, 20));
        this.m.setX(461.0f);
        this.m.setY(88.0f);
        this.addChild(this.m);
        this.n = new Image(new TextureRegion(256, 912, 22, 20));
        this.n.setX(461.0f);
        this.n.setY(120.0f);
        this.addChild(this.n);
        this.o = new Image(new TextureRegion(256, 912, 22, 20));
        this.o.setX(461.0f);
        this.o.setY(152.0f);
        this.addChild(this.o);
        this.pack();
    }

    public void setStatistics(PlayerStatistics playerStatistics) {
        this.unitsPlayerShadow.setText(String.valueOf(playerStatistics.getDestroyedUnits()));
        this.unitsPlayer.setText(String.valueOf(playerStatistics.getDestroyedUnits()));
        this.unitsEnemyShadow.setText(String.valueOf(playerStatistics.getLostUnits()));
        this.unitsEnemy.setText(String.valueOf(playerStatistics.getLostUnits()));
        this.damagePlayerShadow.setText(TextFormatter.formatTenths(playerStatistics.getDamageInflicted()));
        this.damagePlayer.setText(TextFormatter.formatTenths(playerStatistics.getDamageInflicted()));
        this.damageEnemyShadow.setText(TextFormatter.formatTenths(playerStatistics.getDamageReceived()));
        this.damageEnemy.setText(TextFormatter.formatTenths(playerStatistics.getDamageReceived()));
        this.basesPlayerShadow.setText(String.valueOf(playerStatistics.getBasesCaptured()));
        this.basesPlayer.setText(String.valueOf(playerStatistics.getBasesCaptured()));
        this.basesEnemyShadow.setText(String.valueOf(playerStatistics.getBasesLost()));
        this.basesEnemy.setText(String.valueOf(playerStatistics.getBasesLost()));
        this.m.getRegion().x = 256 + playerStatistics.getUnitsRating() * 23;
        this.n.getRegion().x = 256 + playerStatistics.getDamageRating() * 23;
        this.o.getRegion().x = 256 + playerStatistics.getBasesRating() * 23;
        this.pack();
    }
}

