# Generate AI module function-level map via javap (ASCII only: PowerShell -File
# decodes scripts as ANSI/GBK, so non-ASCII literals would be corrupted).
# Output: <source-root>\13_AI_Module_Function_Map.md
param()

# Portable: derive the deploy root from this script's location (run\ -> <src>\run; its parent holds lib/, jdk/, data/).
# Override with the DSF_ROOT environment variable when the layout differs.
. (Join-Path $PSScriptRoot '_env.ps1')
$classes = Get-DsfClassesDir
$javap = Get-DsfTool 'javap'
$cp    = "$classes;" + (Get-DsfClasspath)
if (-not $javap) { throw 'javap not found (set DSF_JAVA_HOME or JAVA_HOME)' }

$srcRoot = Get-DsfSrcRoot
$aiSrc = Join-Path $srcRoot 'src\com\desertstormfront\ai'
$outDoc = Join-Path $srcRoot '13_AI_Module_Function_Map.md'

$files = Get-ChildItem -Path $aiSrc -Recurse -Filter '*.java' | Sort-Object FullName
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# 13. AI Module Function-Level Map (auto-generated)')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Generated by run\ai-map.ps1 via javap from compiled classes.')
[void]$sb.AppendLine('Architecture: intent -> plan (HTN) -> behavior (BT), orchestrated by AIPlanner.')
[void]$sb.AppendLine()

foreach ($f in $files) {
    $rel = $f.FullName.Substring($aiSrc.Length + 1).Replace('\', '/')
    $fqcn = 'com.desertstormfront.ai.' + (($rel -replace '\.java$', '') -replace '/', '.')
    [void]$sb.AppendLine("## $rel")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('```java')
    $dump = & $javap -cp $cp -protected $fqcn 2>$null
    if ($LASTEXITCODE -eq 0 -and $dump) {
        foreach ($line in $dump) { [void]$sb.AppendLine($line) }
    } else {
        [void]$sb.AppendLine('(no javap output)')
    }
    [void]$sb.AppendLine('```')
    [void]$sb.AppendLine()
}

Set-Content -Path $outDoc -Value $sb.ToString() -Encoding UTF8
Write-Host "AI_MAP_DONE file=$outDoc classes=$($files.Count)"
