# Method-level deobfuscation audit (ASCII only).
#
# Uses javap on the compiled classes to count how many methods still carry an
# obfuscated name (1-2 letters, upper OR lower case: the obfuscator used both, e.g.
# Unit.k() and Unit.C() coexist).
# Text scanning the sources would be unreliable; javap signatures are exact.
#
# NOTE: the pattern used to be lowercase-only, which under-counted the real gap by the
# single-uppercase methods (A/C/G/I/J/K/M/N/O/P/Q/R/S/U/V/W/X on Unit alone). Numbers
# produced before this change are therefore not comparable with newer ones.
#
# Output: run\deobf-audit.md
param()

# Portable: derive the deploy root from this script's location (run\ -> <src>\run; its parent holds lib/, jdk/, data/).
# Override with the DSF_ROOT environment variable when the layout differs.
. (Join-Path $PSScriptRoot '_env.ps1')
$classes = Get-DsfClassesDir
$javap   = Get-DsfTool 'javap'
$cp      = "$classes;" + (Get-DsfClasspath)
if (-not $javap) { throw 'javap not found (set DSF_JAVA_HOME or JAVA_HOME)' }

$srcRoot = Get-DsfSrcRoot
$outFile = Join-Path $srcRoot 'run\deobf-audit.md'

if (-not (Test-Path $classes)) { throw "missing build output: $classes (run build.ps1 first)" }

# Short names that are legitimate Java rather than obfuscation artifacts.
$allow = @('if', 'do', 'for', 'of', 'is', 'to', 'at', 'on', 'in', 'x', 'y', 'z', 'id', 'ok')

$files = Get-ChildItem -Path $classes -Recurse -Filter '*.class' | Sort-Object FullName
$total   = 0
$obf     = 0
$fTotal  = 0
$fObf    = 0
$perPkg  = @{}
$perCls  = @{}
$perClsF = @{}

foreach ($f in $files) {
    $rel  = $f.FullName.Substring($classes.Length + 1) -replace '\\', '.'
    $fqcn = $rel -replace '\.class$', ''
    $simple = $fqcn.Substring($fqcn.LastIndexOf('.') + 1)

    $dump = & $javap -p -cp $cp $fqcn 2>$null
    if (-not $dump) { continue }

    $clsTotal = 0
    $clsObf   = 0
    $clsFTotal = 0
    $clsFObf   = 0
    foreach ($line in $dump) {
        if ($line -notmatch '\(') {
            # Field declaration ("private long g;"). Excludes javap metadata ("descriptor: J",
            # "flags: ACC_PRIVATE") and wrapped continuations, which contain , { } or ( ).
            $raw = $line.Trim()
            if ($raw -eq '' -or -not $raw.EndsWith(';')) { continue }
            if ($raw -match '^[A-Za-z_]\w*\s*:' -or $raw -match '[(),{}]') { continue }
            $head = ($raw.TrimEnd(';')).Trim()
            if ($head -eq '') { continue }
            $fname = (($head -split '\s+')[-1]) -replace '\[\]$', ''
            if ($fname -eq $simple) { continue }
            $clsFTotal++
            $fTotal++
            if ($fname -cmatch '^[A-Za-z]{1,2}$' -and $allow -notcontains $fname) {
                $clsFObf++
                $fObf++
            }
            continue
        }
        if ($line -match '^\s+(?:public\s+|protected\s+|private\s+)?(?:static\s+|final\s+|abstract\s+|native\s+|synchronized\s+|transient\s+|volatile\s+)*(?:<[^>]+>\s+)?[\w$.\[\]<>]+[\s<]+([\w$]+)\s*\(') {
            $name = $Matches[1]
            if ($name -eq $simple) { continue }          # constructor
            if ($name -eq '<init>' -or $name -eq '<clinit>') { continue }
            $clsTotal++
            $total++
            if ($name -cmatch '^[A-Za-z]{1,2}$' -and $allow -notcontains $name) {
                $clsObf++
                $obf++
            }
        }
    }

    if ($clsTotal -gt 0) {
        $pkg = $fqcn
        if ($pkg -match '^com\.desertstormfront\.([a-z]+)') { $pkg = 'com.desertstormfront.' + $Matches[1] }
        elseif ($pkg -match '^com\.noblemaster\.lib\.([a-z]+)') { $pkg = 'com.noblemaster.lib.' + $Matches[1] }
        else { $pkg = ($fqcn.Split('.')[0..2] -join '.') }
        if (-not $perPkg.ContainsKey($pkg)) { $perPkg[$pkg] = @(0, 0, 0, 0) }
        $perPkg[$pkg][0] += $clsTotal
        $perPkg[$pkg][1] += $clsObf
        $perPkg[$pkg][2] += $clsFTotal
        $perPkg[$pkg][3] += $clsFObf
        if ($clsObf -gt 0) { $perCls[$fqcn] = @($clsTotal, $clsObf) }
        if ($clsFObf -gt 0) { $perClsF[$fqcn] = @($clsFTotal, $clsFObf) }
    }
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# Method-level deobfuscation audit (auto-generated)')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Generated by `run\deobf-audit.ps1` via javap over the compiled classes.')
[void]$sb.AppendLine('An obfuscated name is 1-2 letters, upper or lower case (the obfuscator used both); constructors and')
[void]$sb.AppendLine('`<init>/<clinit>` are excluded. Fields are counted the same way, so a renamed field does not')
[void]$sb.AppendLine('hide behind a semantic getter.')
[void]$sb.AppendLine()
[void]$sb.AppendLine("classes scanned : $($files.Count)")
[void]$sb.AppendLine("methods total   : $total")
[void]$sb.AppendLine("obfuscated      : $obf")
if ($total -gt 0) {
    [void]$sb.AppendLine(("obfuscated pct  : {0:N1}%" -f (100 * $obf / $total)))
}
[void]$sb.AppendLine("fields total    : $fTotal")
[void]$sb.AppendLine("fields obfusc.  : $fObf")
if ($fTotal -gt 0) {
    [void]$sb.AppendLine(("fields obf.pct  : {0:N1}%" -f (100 * $fObf / $fTotal)))
}
[void]$sb.AppendLine()
[void]$sb.AppendLine('## By package')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| package | methods | obfuscated | pct | fields | obfuscated | pct |')
[void]$sb.AppendLine('|---|---|---|---|---|---|---|')
foreach ($k in ($perPkg.Keys | Sort-Object { -($perPkg[$_][1] + $perPkg[$_][3]) })) {
    $t = $perPkg[$k][0]; $o = $perPkg[$k][1]; $ft = $perPkg[$k][2]; $fo = $perPkg[$k][3]
    $pct = if ($t -gt 0) { 100 * $o / $t } else { 0 }
    $fpct = if ($ft -gt 0) { 100 * $fo / $ft } else { 0 }
    [void]$sb.AppendLine(("| {0} | {1} | {2} | {3:N0}% | {4} | {5} | {6:N0}% |" -f $k, $t, $o, $pct, $ft, $fo, $fpct))
}
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Top 25 classes by obfuscated method count')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| class | methods | obfuscated |')
[void]$sb.AppendLine('|---|---|---|')
$top = $perCls.Keys | Sort-Object { -$perCls[$_][1] } | Select-Object -First 25
foreach ($k in $top) {
    [void]$sb.AppendLine(("| {0} | {1} | {2} |" -f $k, $perCls[$k][0], $perCls[$k][1]))
}
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Top 15 classes by obfuscated field count')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| class | fields | obfuscated |')
[void]$sb.AppendLine('|---|---|---|')
$topF = $perClsF.Keys | Sort-Object { -$perClsF[$_][1] } | Select-Object -First 15
foreach ($k in $topF) {
    [void]$sb.AppendLine(("| {0} | {1} | {2} |" -f $k, $perClsF[$k][0], $perClsF[$k][1]))
}

Set-Content -Path $outFile -Value $sb.ToString() -Encoding UTF8
Write-Host "DEOBF_AUDIT_DONE file=$outFile methods=$total obfuscated=$obf fields=$fTotal fobf=$fObf"
